import type { WorkItem } from '../types';

// Sample data representing HouseSigma's opportunity tree
export const sampleData: WorkItem[] = [
  // Mission - Top level
  {
    id: 'mission-1',
    title: 'Revolutionize Canadian Real Estate Experience',
    type: 'mission',
    status: 'In Progress',
    priority: 'P0',
    progress: 45,
    owner: { id: 'owner-1', name: 'Alfred', email: 'alfred@housesigma.com' },
    children: ['problem-1', 'problem-2', 'problem-3'],
    createdAt: '2024-01-01',
    updatedAt: '2024-12-15',
    tags: ['mission', 'company-wide'],
  },

  // Problems under Mission
  {
    id: 'problem-1',
    title: 'Users cannot easily find comparable property prices',
    type: 'problem',
    status: 'In Progress',
    priority: 'P0',
    progress: 60,
    owner: { id: 'owner-2', name: 'TanWei', email: 'tanwei@housesigma.com' },
    parentId: 'mission-1',
    children: ['solution-1', 'solution-2'],
    description: 'Users struggle to find and compare property prices in their target neighborhoods',
    createdAt: '2024-02-01',
    updatedAt: '2024-12-14',
    tags: ['user-experience', 'pricing'],
  },
  {
    id: 'problem-2',
    title: 'Agent productivity is limited by manual processes',
    type: 'problem',
    status: 'Blocked',
    priority: 'P1',
    progress: 25,
    owner: { id: 'owner-3', name: 'Reed', email: 'reed@housesigma.com' },
    parentId: 'mission-1',
    children: ['solution-3'],
    blockedBy: ['solution-1'],
    description: 'Agents spend too much time on manual data entry and client communication',
    createdAt: '2024-03-01',
    updatedAt: '2024-12-10',
    tags: ['agent-tools', 'automation'],
  },
  {
    id: 'problem-3',
    title: 'Market insights are not actionable for buyers',
    type: 'problem',
    status: 'Not Started',
    priority: 'P2',
    progress: 0,
    owner: { id: 'owner-4', name: 'Joseph', email: 'joseph@housesigma.com' },
    parentId: 'mission-1',
    children: ['solution-4'],
    description: 'Buyers get overwhelmed with data but lack clear guidance on timing and pricing',
    createdAt: '2024-04-01',
    updatedAt: '2024-12-01',
    tags: ['market-insights', 'buyer-experience'],
  },

  // Solutions under Problem 1
  {
    id: 'solution-1',
    title: 'AI-powered price comparison engine',
    type: 'solution',
    status: 'In Progress',
    priority: 'P0',
    progress: 75,
    owner: { id: 'owner-2', name: 'TanWei', email: 'tanwei@housesigma.com' },
    parentId: 'problem-1',
    children: ['design-1', 'project-1', 'project-2'],
    description: 'Use machine learning to provide accurate price comparisons based on multiple factors',
    createdAt: '2024-03-15',
    updatedAt: '2024-12-14',
    tags: ['AI', 'pricing', 'MVP'],
  },
  {
    id: 'solution-2',
    title: 'Neighborhood price heatmap',
    type: 'solution',
    status: 'In Review',
    priority: 'P1',
    progress: 90,
    owner: { id: 'owner-3', name: 'Reed', email: 'reed@housesigma.com' },
    parentId: 'problem-1',
    children: ['design-2', 'project-3'],
    description: 'Visual heatmap showing price trends across neighborhoods',
    createdAt: '2024-04-01',
    updatedAt: '2024-12-12',
    tags: ['visualization', 'maps'],
  },

  // Solution under Problem 2
  {
    id: 'solution-3',
    title: 'Automated client communication system',
    type: 'solution',
    status: 'Blocked',
    priority: 'P1',
    progress: 30,
    owner: { id: 'owner-3', name: 'Reed', email: 'reed@housesigma.com' },
    parentId: 'problem-2',
    children: ['design-3'],
    blockedBy: ['solution-1'],
    description: 'Automated email and notification system for client updates',
    createdAt: '2024-05-01',
    updatedAt: '2024-12-08',
    tags: ['automation', 'communication'],
  },

  // Solution under Problem 3
  {
    id: 'solution-4',
    title: 'Market timing recommendation engine',
    type: 'solution',
    status: 'Not Started',
    priority: 'P2',
    progress: 0,
    owner: { id: 'owner-4', name: 'Joseph', email: 'joseph@housesigma.com' },
    parentId: 'problem-3',
    children: [],
    description: 'AI-powered recommendations for optimal buying/selling timing',
    createdAt: '2024-06-01',
    updatedAt: '2024-12-01',
    tags: ['AI', 'market-timing'],
  },

  // Designs
  {
    id: 'design-1',
    title: 'Price comparison UI wireframes',
    type: 'design',
    status: 'Done',
    priority: 'P0',
    progress: 100,
    owner: { id: 'owner-5', name: 'Design Team', email: 'design@housesigma.com' },
    parentId: 'solution-1',
    children: [],
    description: 'Wireframes and mockups for the price comparison interface',
    createdAt: '2024-04-01',
    updatedAt: '2024-10-15',
    tags: ['UI', 'wireframes'],
  },
  {
    id: 'design-2',
    title: 'Heatmap visualization design',
    type: 'design',
    status: 'Done',
    priority: 'P1',
    progress: 100,
    owner: { id: 'owner-5', name: 'Design Team', email: 'design@housesigma.com' },
    parentId: 'solution-2',
    children: [],
    description: 'Visual design for neighborhood price heatmaps',
    createdAt: '2024-05-01',
    updatedAt: '2024-09-20',
    tags: ['UI', 'maps', 'visualization'],
  },
  {
    id: 'design-3',
    title: 'Communication templates',
    type: 'design',
    status: 'In Progress',
    priority: 'P1',
    progress: 50,
    owner: { id: 'owner-5', name: 'Design Team', email: 'design@housesigma.com' },
    parentId: 'solution-3',
    children: [],
    description: 'Email and notification templates for automated communication',
    createdAt: '2024-07-01',
    updatedAt: '2024-12-05',
    tags: ['templates', 'email'],
  },

  // Projects
  {
    id: 'project-1',
    title: 'ML model training pipeline',
    type: 'project',
    status: 'In Progress',
    priority: 'P0',
    progress: 80,
    owner: { id: 'owner-2', name: 'TanWei', email: 'tanwei@housesigma.com' },
    parentId: 'solution-1',
    children: [],
    dueDate: '2024-12-30',
    description: 'Build and train the ML model for price prediction',
    createdAt: '2024-06-01',
    updatedAt: '2024-12-14',
    tags: ['ML', 'backend'],
  },
  {
    id: 'project-2',
    title: 'Price comparison API development',
    type: 'project',
    status: 'In Progress',
    priority: 'P0',
    progress: 65,
    owner: { id: 'owner-6', name: 'Backend Team', email: 'backend@housesigma.com' },
    parentId: 'solution-1',
    children: [],
    dueDate: '2024-12-25',
    description: 'Develop REST API for price comparison service',
    createdAt: '2024-07-01',
    updatedAt: '2024-12-13',
    tags: ['API', 'backend'],
  },
  {
    id: 'project-3',
    title: 'Heatmap frontend implementation',
    type: 'project',
    status: 'In Review',
    priority: 'P1',
    progress: 95,
    owner: { id: 'owner-7', name: 'Frontend Team', email: 'frontend@housesigma.com' },
    parentId: 'solution-2',
    children: [],
    dueDate: '2024-12-20',
    description: 'Implement the heatmap visualization on the frontend',
    createdAt: '2024-08-01',
    updatedAt: '2024-12-12',
    tags: ['frontend', 'maps'],
  },

  // Additional items to show more complexity
  {
    id: 'problem-4',
    title: 'Data integration challenges with MLS',
    type: 'problem',
    status: 'In Progress',
    priority: 'P1',
    progress: 40,
    owner: { id: 'owner-6', name: 'Backend Team', email: 'backend@housesigma.com' },
    parentId: 'mission-1',
    children: ['solution-5'],
    description: 'MLS data is inconsistent and requires extensive cleaning',
    createdAt: '2024-05-01',
    updatedAt: '2024-12-10',
    tags: ['data', 'integration', 'M3'],
  },
  {
    id: 'solution-5',
    title: 'Automated data cleaning pipeline',
    type: 'solution',
    status: 'In Progress',
    priority: 'P1',
    progress: 55,
    owner: { id: 'owner-6', name: 'Backend Team', email: 'backend@housesigma.com' },
    parentId: 'problem-4',
    children: ['project-4', 'project-5'],
    description: 'Build automated ETL pipeline for MLS data cleaning',
    createdAt: '2024-06-15',
    updatedAt: '2024-12-10',
    tags: ['ETL', 'data'],
  },
  {
    id: 'project-4',
    title: 'ETL infrastructure setup',
    type: 'project',
    status: 'Done',
    priority: 'P1',
    progress: 100,
    owner: { id: 'owner-6', name: 'Backend Team', email: 'backend@housesigma.com' },
    parentId: 'solution-5',
    children: [],
    description: 'Set up Apache Airflow for ETL orchestration',
    createdAt: '2024-07-01',
    updatedAt: '2024-11-01',
    tags: ['infrastructure', 'ETL'],
  },
  {
    id: 'project-5',
    title: 'Data validation rules engine',
    type: 'project',
    status: 'In Progress',
    priority: 'P1',
    progress: 70,
    owner: { id: 'owner-6', name: 'Backend Team', email: 'backend@housesigma.com' },
    parentId: 'solution-5',
    children: [],
    dueDate: '2024-12-28',
    description: 'Build rules engine for MLS data validation',
    createdAt: '2024-09-01',
    updatedAt: '2024-12-10',
    tags: ['validation', 'data', 'M3'],
  },
];

export default sampleData;
